# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reminder < Formula
  desc "Terminal-based interactive app for organising tasks with minimal efforts."
  homepage "https://github.com/goyalmunish/reminder"
  version "1.9.25"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.25/reminder_1.9.25_darwin_arm64.tar.gz"
      sha256 "5aa4cd380b08ff7d3c5615e04b086a60a1131159bacf188787d0a7985d119d60"

      def install
        bin.install "reminder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.25/reminder_1.9.25_darwin_amd64.tar.gz"
      sha256 "385c96f289b14786302871f0b94dab8c6c0ca54924d1379ea53d2545bac1705e"

      def install
        bin.install "reminder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.25/reminder_1.9.25_linux_arm64.tar.gz"
      sha256 "f61da42e6073ae8a4d7edcf8a28251aec5b5f8fd95533c5042b8040821d8711b"

      def install
        bin.install "reminder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.25/reminder_1.9.25_linux_amd64.tar.gz"
      sha256 "e14dfae63aa23e27493d5c2a955e470b934b963377cfe636113de95749970ea2"

      def install
        bin.install "reminder"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
