# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reminder < Formula
  desc "Terminal-based interactive app for organising tasks with minimal efforts."
  homepage "https://github.com/goyalmunish/reminder"
  version "1.9.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.14/reminder_1.9.14_darwin_amd64.tar.gz"
      sha256 "884adc0d17e28fe3a072416e1d9464b244ac44fac9c6a4036dfe429129e7ec91"

      def install
        bin.install "reminder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.14/reminder_1.9.14_darwin_arm64.tar.gz"
      sha256 "bdc01b112a46c6b11e5b28cb5811c246077bb8d11c278232f2a42e19a7e35412"

      def install
        bin.install "reminder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.14/reminder_1.9.14_linux_arm64.tar.gz"
      sha256 "15554f9995efe20a0ca46e3aac1ef7331311cde53c288e489ab82de1caead5a3"

      def install
        bin.install "reminder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goyalmunish/reminder/releases/download/v1.9.14/reminder_1.9.14_linux_amd64.tar.gz"
      sha256 "423555d4bb87b080d22d623ebccc0f84c65c40bf4c6fe7ef96ead6256e3d5d97"

      def install
        bin.install "reminder"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
